### ISSUE TITLE
WebpackAutoInject is not a contructor

### ISSUE THREAD

**Issue by nsteenbeek** [radswiat/webpack-auto-inject-version#12]
Hi,

I'm getting error as shown below. I could fix/hack-around this by using
  * new WebpackAutoInject.default();

Probably due to exporting as default
```javascript
export default class WebpackAutoInject.
```

## Error

C:\myfolder\webpack.config.js:58
        new WebpackAutoInject(),
        ^

TypeError: WebpackAutoInject is not a constructor
    at Object.<anonymous> (C:\myfolder\webpack.config.js:58:9)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at requireConfig (C:\myfolder\node_modules\webpack\bin\convert-argv.js:96:18)
    at C:\myfolder\node_modules\webpack\bin\convert-argv.js:109:17

**Comment by radswiat** [comment]
Hey, are you importing it correctly ? 
Demo shows the correct way for it when documentation was wrong ( updated just now ),
```
var WebpackAutoInject = require('webpack-auto-inject-version').default;
```

**Comment by nsteenbeek** [comment]
I posted this issue just before you updated the documentation :).
