### ISSUE TITLE
Error in 0.5.5

### ISSUE THREAD

**Issue by timothyblue** [radswiat/webpack-auto-inject-version#15]
I was so happy and then I saw this...

Any ideas?

```
[AIV] :  info : InjectAsComment : match : app.css : injected : 1.0.16
 95% emittingUnhandled rejection TypeError: asset.source(...).replace is not a function
    at C:\data\web\damage\node_modules\webpack-auto-inject-version\dist\WebpackAutoInjectVersion.js:649:44
    at Compiler.<anonymous> (C:\data\web\damage\node_modules\webpack-auto-inject-version\dist\WebpackAutoInjectVersion.js:657:15)
    at next (C:\data\web\damage\node_modules\tapable\lib\Tapable.js:140:14)
    at Compiler.<anonymous> (C:\data\web\damage\node_modules\webpack\lib\ProgressPlugin.js:126:5)
    at next (C:\data\web\damage\node_modules\tapable\lib\Tapable.js:140:14)
    at C:\data\web\damage\node_modules\html-webpack-plugin\index.js:205:9
    at PassThroughHandlerContext.finallyHandler (C:\data\web\damage\node_modules\bluebird\js\release\finally.js:56:23)
    at PassThroughHandlerContext.tryCatcher (C:\data\web\damage\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\data\web\damage\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\data\web\damage\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\data\web\damage\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\data\web\damage\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\data\web\damage\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\data\web\damage\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\data\web\damage\node_modules\bluebird\js\release\async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by kidroca** [comment]
This is reported here #13 and should be fixed by #14 
I just checked the latest version on npm (0.5.5) it does **not** contain the fix
I think the new package with the fix is not released yet

**Comment by timothyblue** [comment]
OK. I used npm to install the latest version this morning. This would explain it.  I will wait until the package is updated. Thanks!

**Comment by radswiat** [comment]
It should be fine now,
but please be aware that .default is gone now.
You should require by old ( better ) way:
```js
var WebpackAutoInject = require('webpack-auto-inject-version');
```
Also the problem with missing modules should be fixed now - at least its fine when i'm testing it on fresh project.
Thanks
