### ISSUE TITLE
Deprecation Warning with Webpack 4

### ISSUE THREAD

**Issue by MarkThibault** [radswiat/webpack-auto-inject-version#32]
Hello!

I recently upgraded my app to Webpack 4 and started getting this Deprecation Warning:

`DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
    at InjectAsComment.apply (/Users/mthib2/Projects/app/node_modules/webpack-auto-inject-version/dist/WebpackAutoInjectVersion.js:3241:29)
    at WebpackAutoInject._executeComponent (/Users/mthib2/Projects/app/node_modules/webpack-auto-inject-version/dist/WebpackAutoInjectVersion.js:2879:12)
    at WebpackAutoInject._executeWebpackComponents (/Users/mthib2/Projects/app/node_modules/webpack-auto-inject-version/dist/WebpackAutoInjectVersion.js:2844:12)
    at WebpackAutoInject.apply (/Users/mthib2/Projects/app/node_modules/webpack-auto-inject-version/dist/WebpackAutoInjectVersion.js:2817:12)
    at webpack (/Users/mthib2/Projects/app/node_modules/webpack/lib/webpack.js:37:12)
    at processOptions (/Users/mthib2/Projects/app/node_modules/webpack-cli/bin/webpack.js:436:16)
    at yargs.parse (/Users/mthib2/Projects/app/node_modules/webpack-cli/bin/webpack.js:512:3)
    at Object.parse (/Users/mthib2/Projects/app/node_modules/yargs/yargs.js:552:18)
    at /Users/mthib2/Projects/app/node_modules/webpack-cli/bin/webpack.js:217:8
    at Object.<anonymous> (/Users/mthib2/Projects/app/node_modules/webpack-cli/bin/webpack.js:514:3)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/mthib2/Projects/app/node_modules/webpack/bin/webpack.js:80:2)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3`

Cheers,
Mark

**Comment by warm200** [comment]
same issue here

**Comment by mark-raymond** [comment]
I have made a PR to fix this here: #41

**Comment by nicewaytodoit** [comment]
PR #41 has wrong syntax and it will cause build to fail with syntax error, new PR raised #43 .

**Comment by Zireael** [comment]
Getting this comment when using Vue CLI as well:
```
$ vue-cli-service build --mode production --dest _production --target app --modern --dashboard
[AIV] :  info : DEMO AIV started
-  Building legacy bundle for production...
(node:19160) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
```
