### ISSUE TITLE
webpack-auto-inject-version doesn't work with webpack 5

### ISSUE THREAD

**Issue by vitaliymaz** [radswiat/webpack-auto-inject-version#52]
Auto inject version started
[webpack-cli] TypeError: this.context.compiler.plugin is not a function
    at InjectAsComment.apply (/home/vmazurenko/Documents/projects/qsc/ui/node_modules/webpack-auto-inject-version/dist/WebpackAutoInjectVersion.js:3279:29)
    at WebpackAutoInject._executeComponent (/home/vmazurenko/Documents/projects/qsc/ui/node_modules/webpack-auto-inject-version/dist/WebpackAutoInjectVersion.js:2891:12)
    at WebpackAutoInject._executeWebpackComponents (/home/vmazurenko/Documents/projects/qsc/ui/node_modules/webpack-auto-inject-version/dist/WebpackAutoInjectVersion.js:2856:12)
    at WebpackAutoInject.apply (/home/vmazurenko/Documents/projects/qsc/ui/node_modules/webpack-auto-inject-version/dist/WebpackAutoInjectVersion.js:2829:12)
    at createCompiler (/home/vmazurenko/Documents/projects/qsc/ui/node_modules/webpack/lib/webpack.js:74:12)
...

**Comment by bflamand** [comment]
yes, please add support for webpack 5...

**Comment by clark-stevenson** [comment]
I had no choice but to update recently. I did the following but note that I am using TypeScript although I am sure changing the `ts` to `js` extension would cause no concerns and also, it depends on what you were using this plugin for.

In my `package.json` to the `scripts` property I added a `gen-version` command. 
 
```json
    scripts: {
        "gen-version": "node -p \"'export const VERSION = ' + JSON.stringify(require('./package.json').version) + ';'\" > src/version.ts",
    }
```

This generates a `./src/version.ts` with the following that I can import as taken from the `package.json` and used within my code.

```typescript
    export const VERSION = "3.0.0";
```

Example:

```typescript
import { VERSION } from "./version"
export const LibVersion =  `Heyyyy this is version ${VERSION} 😁`
```

In my case I use `npm run build:patch` `npm run build:minor` and `npm run build:major`

```json
    scripts: {
        "gen-version": "node -p \"'export const VERSION = ' + JSON.stringify(require('./package.json').version) + ';'\" > src/version.ts",
        "build:patch": "npm version patch --no-git-tag-version --force && npm run gen-version && npm run webpack" 
    }
```

 Where:

1. `npm version patch --no-git-tag-version` is a native npm command which doesn't commit and is forced.
2.  Where the now updated `package.json version` is dumped to `./src/version.ts`
3.  Where I can use that in my build for logging.

**Comment by CharlyPoppins** [comment]
The library seems unmaintained , have a look at https://github.com/radswiat/webpack-auto-inject-version/pull/51
