### ISSUE TITLE
argsv.env[arg] fails

### ISSUE THREAD

**Issue by nsteenbeek** [radswiat/webpack-auto-inject-version#9]
Hi,

I'm getting an error on webpack 2.

## Package.json:
  * devDependencies: 
    * webpack: 2.3.3
    * webpack-auto-inject-version: 0.5.1
  * version: "0.2.0"

## Webpack.config.js
  * WebpackAutoInject = require("webpack-auto-inject-version");
  * plugins: [new WebpackAutoInject()]

## Log

C:\myfolder\node_modules\webpack-auto-inject-version\dist\WebpackAutoInjectVersion.js:276
  return Boolean(argv.env[arg]);
                         ^

TypeError: Cannot read property 'aiv-log-full' of undefined
    at isArgv (C:\myfolder\node_modules\node_modules\webpack-auto-inject-version\dist\WebpackAutoInjectVersion.js:276:26)
    at Log.getLogLevel (C:\myfolder\node_modules\node_modules\webpack-auto-inject-version\dist\WebpackAutoInjectVersion.js:
170:29)
    at new Log (C:\myfolder\node_modules\node_modules\webpack-auto-inject-version\dist\WebpackAutoInjectVersion.js:164:10)
    at Object.<anonymous> (C:\myfolder\node_modules\node_modules\webpack-auto-inject-version\dist\WebpackAutoInjectVersion.
js:233:19)
    at __webpack_require__ (C:\myfolder\node_modules\node_modules\webpack-auto-inject-version\dist\WebpackAutoInjectVersion
.js:30:30)
    at Object.<anonymous> (C:\myfolder\node_modules\node_modules\webpack-auto-inject-version\dist\WebpackAutoInjectVersion.
js:728:12)
    at __webpack_require__ (C:\myfolder\node_modules\node_modules\webpack-auto-inject-version\dist\WebpackAutoInjectVersion
.js:30:30)
    at C:\myfolder\node_modules\node_modules\webpack-auto-inject-version\dist\WebpackAutoInjectVersion.js:76:18
    at C:\myfolder\node_modules\node_modules\webpack-auto-inject-version\dist\WebpackAutoInjectVersion.js:79:10
    at webpackUniversalModuleDefinition (C:\myfolder\node_modules\node_modules\webpack-auto-inject-version\dist\WebpackAuto
InjectVersion.js:3:20)

**Comment by radswiat** [comment]
Sorry for that, 
it should be fine now ( v 0.5.3 )
